scalars:
  UnsignedInt64: int
  BigInt: int
  Date: string
  ISO8601DateTime: string
  DateTime: string
  URL: string
  FormattedString: string
  HTML: string
  ARN: string
  UtcOffset: string
  Color: string
  StorefrontID: string
  Decimal: 'float|string'
  Money: 'float|string'
  JSON: mixed

sources:
  AdminApi:
    namespace: Shopify\Types\AdminApi
    url: https://shopify.dev/admin-graphql-direct-proxy/2026-04
    extensions:
      - ./custom.graphql

  StorefrontApi:
    namespace: Shopify\Types\StorefrontApi
    url: https://shopify.dev/storefront-graphql-direct-proxy/2026-04
